{
  "formatVersion": "1.1",
  "component": {
    "url": "../../richeditor-compose/1.0.0-rc12/richeditor-compose-1.0.0-rc12.module",
    "group": "com.mohamedrejeb.richeditor",
    "module": "richeditor-compose",
    "version": "1.0.0-rc12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "richeditor-compose-release.aar",
          "url": "richeditor-compose-android-1.0.0-rc12.aar",
          "size": 498544,
          "sha512": "59dfe64af2e472c2c0ead8ab5005c2d0979c54a881486d599a8ef775c8b5a7a13e7c3658c735e4644b877fcba8f6313462350cf7ebe571e3543a8c2b26ecee75",
          "sha256": "1724a31c60e78ed864c2ff67e8d2a824c3d3dbf26f87212442107c69a8804a13",
          "sha1": "6a1b625e10460e358004a6bf1573d24d9ac427dc",
          "md5": "709be4b3bcea88bb7507738f6623ae50"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mohamedrejeb.ksoup",
          "module": "ksoup-html",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mohamedrejeb.ksoup",
          "module": "ksoup-entities",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "markdown",
          "version": {
            "requires": "0.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "richeditor-compose-release.aar",
          "url": "richeditor-compose-android-1.0.0-rc12.aar",
          "size": 498544,
          "sha512": "59dfe64af2e472c2c0ead8ab5005c2d0979c54a881486d599a8ef775c8b5a7a13e7c3658c735e4644b877fcba8f6313462350cf7ebe571e3543a8c2b26ecee75",
          "sha256": "1724a31c60e78ed864c2ff67e8d2a824c3d3dbf26f87212442107c69a8804a13",
          "sha1": "6a1b625e10460e358004a6bf1573d24d9ac427dc",
          "md5": "709be4b3bcea88bb7507738f6623ae50"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "richeditor-compose-android-1.0.0-rc12-sources.jar",
          "url": "richeditor-compose-android-1.0.0-rc12-sources.jar",
          "size": 122161,
          "sha512": "fc2bb345f7c3783b1a219f70623c1813a4238aa5ce93201152c040c33091db88bac921f1ef6df23575ed0ace534f04f7d483b0d9492f4515a689787e014740d3",
          "sha256": "5c58a585b1231dd252a5470a761fb6e5d620227bd6cd54c17bcb4c7c9f13a8a0",
          "sha1": "a930731a471434b1efcc0ce4be7d5e6edfd961f3",
          "md5": "b032aa9fa5fdddb18c445d52ccc69aee"
        }
      ]
    }
  ]
}
